version: "3.8"

services:
    nginx-proxy:
        image: nginx:latest
        ports:
            - "3000:80"
            - "8080:8080" # Expose 8080
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend-container
            - frontend-container
        networks:
            - projet
    mysql-container:
        image: mysql
        environment:
            MYSQL_DATABASE: "crud"
            MYSQL_ROOT_PASSWORD: "root"
        networks:
            - projet
        volumes:
            - my-db:/var/lib/mysql
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "0.75"
                    memory: 768M
            restart_policy:
                condition: on-failure

    backend-container:
        image: backend-image
        depends_on:
            - mysql-container
        networks:
            - projet
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "1"
                    memory: 1024M
            restart_policy:
                condition: on-failure

    frontend-container:
        image: frontend-image
        networks:
            - projet
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
            restart_policy:
                condition: on-failure

networks:
    projet:
        driver: overlay

volumes:
    my-db:
        driver: local
