version: "3.9"

services:
    mysql:
        image: localhost/mysql
        container_name: mysql-container
        restart: always
        environment:
            MYSQL_DATABASE: "crud"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - projet
        ports:
            - "3307:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql

    backend:
        image: backend-image
        container_name: backend-container
        depends_on:
            - mysql
        networks:
            - projet
        ports:
            - "8080:8080"

    frontend:
        image: frontend-image
        container_name: frontend-container
        networks:
            - projet
        ports:
            - "3000:80"

networks:
    projet:
        driver: bridge

volumes:
    my-db:
        driver: local
