apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: mysql-pdb
    namespace: exam
spec:
    minAvailable: 1 # Ensure at least one MySQL pod is available at all times
    selector:
        matchLabels:
            app: mysql
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: frontend-pdb
    namespace: exam
spec:
    minAvailable: 1 # Ensure at least one Frontend pod is available at all times
    selector:
        matchLabels:
            app: frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: backend-pdb
    namespace: exam
spec:
    minAvailable: 1 # Ensure at least one Backend pod is available at all times
    selector:
        matchLabels:
            app: backend
