apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    namespace: exam
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: damarcusthefifthpromax/backend-image:latest
                  ports:
                      - containerPort: 8080
                  env:
                      - name: DB_HOST
                        value: "mysql-service"
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: username
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: password
