apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: my-crud-ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: frontend.local
          http:
              paths:
                  - path: /(.*)\.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg)$
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: frontend-service
                            port:
                                number: 80
                  - path: /(.*) # Everything else
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: frontend-service
                            port:
                                number: 80
