apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: my-crud-ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: frontend.local
          http:
              paths:
                  - path: /?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend-service
                            port:
                                number: 80
