apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-statefulset
    namespace: exam
spec:
    serviceName: mysql-service
    replicas: 2
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql
                  ports:
                      - containerPort: 3306
                  livenessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -u
                              - root
                              - -p$(MYSQL_ROOT_PASSWORD)
                      initialDelaySeconds: 10
                      periodSeconds: 20
                      failureThreshold: 3
                  readinessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -u
                              - root
                              - -p$(MYSQL_ROOT_PASSWORD)
                      initialDelaySeconds: 10
                      periodSeconds: 20
                      failureThreshold: 3
                  startupProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -u
                              - root
                              - -p$(MYSQL_ROOT_PASSWORD)
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      failureThreshold: 30
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: root-password
                      - name: MYSQL_DATABASE
                        value: "crud"
                  volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
                  resources:
                      limits:
                          limits:
                          memory: "512Mi" # Memory limit (maximum resource)
                          cpu: "250m"
    volumeClaimTemplates:
        - metadata:
              name: mysql-data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 1Gi
